---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: false
  grep:
    enabled: false
  markdownlint:
    enabled: false
  nodesecurity:
    enabled: true
  requiresafe:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- .serverless/
- .webpack/
- coverage/
- node_modules/
- test/
