service:
  name: aws-nodejs-ecma-script



provider:
  name: aws
  runtime: nodejs6.10

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  health:
    handler: handler.health
    events:
      - http:
          method: get
          path: health
