service:
  name: serverless-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: dev
  cfLogs: true
  environment:
    MY_KMS_SECRET: ${self:custom.kmsSecrets.secrets.foo}
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
    SERVERLESS_PROJECT: ${self:service}

  iamRoleStatements:
  # - Effect: Allow
  #   Action:
  #     - KMS:Decrypt
  #   Resource: ${self:custom.kmsSecrets.keyArn}


plugins:
  - serverless-kms-secrets
  - serverless-jest-plugin
  - serverless-webpack
  - serverless-offline


custom:
  # preTestCommands:
  #   - bash .tools/startOffline.sh
  # postTestCommands:
  #   - bash .tools/stopOffline.sh
  webpackIncludeModules: true

  serverless-jest-plugin:
    functionTemplate: config/templates/function-template.ejs
    testTemplate: config/templates/test-template.ejs

  jest:

  serverless-kms-secrets:
    secretsFile:
    # secretsFile: kms2-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml # (optional)
  # kmsSecrets: ${file(kms-secrets2.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}


functions:

  health:
    handler: handler.health
    events:
      - http:
          method: get
          path: health

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  # kms:
  #   handler: handler.kms
  #   events:
  #     - http:
  #         method: get
  #         path: kms
