service:
  name: serverless-boilerplate

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: dev
  cfLogs: true
  environment:
    # MY_KMS_SECRET: ${self:custom.kmsSecrets.secrets.foo}
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
    SERVERLESS_PROJECT: ${self:service}

  iamRoleStatements:
  - Effect: Allow
  Action:
    - dynamodb:*
  Resource: arn:aws:dynamodb:*:*:table/${self:custom.table_name}
  # - Effect: Allow
  #   Action:
  #     - KMS:Decrypt
  #   Resource: ${self:custom.kmsSecrets.keyArn}


plugins:
  - serverless-aws-documentation
  - serverless-kms-secrets
  - serverless-jest-plugin
  - dynalite
  - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline


custom:
  table_name: ${self:service}-table
  # preTestCommands:
  #   - bash .tools/startOffline.sh
  # postTestCommands:
  #   - bash .tools/stopOffline.sh
  webpackIncludeModules: true

  serverless-jest-plugin:
    functionTemplate: config/templates/function-template.ejs
    testTemplate: config/templates/test-template.ejs

  serverless-kms-secrets:
    secretsFile:
    # secretsFile: kms2-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml # (optional)
  # kmsSecrets: ${file(kms-secrets2.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true

  documentation:
    api:
      info:
        ${file(lib/docs/info.yml)}
    tags:
      - name: MyTag
        description: This is my tag
    resources:
      - path: '/health'
        description: 'Endpoint to see if the serverless app is working'
      - path: '/hello'
        description: 'Joyful greeting by your Serverless Application'
    models:
      - ${file(lib/docs/models/200SuccessResponse.yml)}



functions:
  health:
    handler: handler.health
    events:
      - http:
          method: get
          path: health
          cors: true
          documentation:
            summary: 'GET /health'
            tags:
              - MyTag
            description: 'Check whether your serverless application is working'
            methodResponses:
              - statusCode: '200'
                responseModels:
                  'application/json': SuccessResponse

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          cors: true
          documentation:
            summary: 'GET /hello'
            tags:
              - MyTag
            description: 'Let your serverless application say hello to the world!'
            methodResponses:
              - statusCode: '200'
                responseModels:
                  'application/json': SuccessResponse

  # kms:
  #   handler: handler.kms
  #   events:
  #     - http:
  #         method: get
  #         path: kms


resources:
  Resources:
    serverlessBoilerplateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table_name}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
